Id b 13
AntonZhikin/PetFamily pull request #22
Opened 2024-11-28 10:32 UTC by AntonZhikin

2024-11-28 21:22 UTC, AntonZhikin commented
я слил коммит сюда, с тестовым контролером(посмотрел пока только 11 задание). Но у меня почему то не показывается этот коммит, хотя изменения улетели. Если не тоже не видишь, можешь вручную посмотреть? Все проверил, все работает

2024-11-29 08:51 UTC, KirillSachkov requested changes

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.API/Controllers/ApplicationController.cs
> +[Route("[controller]/pet")]
в главном контроллере не должно быть pet

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +
лишний отступ

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +                .WithBucket("photos");
лучше название бакеты принимать в параметрах

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +                    .WithBucket("photos");
из параметров

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +                .WithBucket("photos")
из параметров

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +                .WithBucket("photos");
из параметров

2024-11-29 08:51 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Providers/MinioProvider.cs
> +            }
можно вынести в отдельный метод приватный, потому что это повторяется

2024-12-01 18:52 UTC, merged