вроде все норм
AntonZhikin/PetFamily pull request #24
Opened 2024-12-11 18:52 UTC by AntonZhikin

ID-b-15

2024-12-11 20:42 UTC, AntonZhikin commented
можно я удалю тестовый контроллер из задания 13 (MInio)?

2024-12-12 08:21 UTC, KirillSachkov commented
> можно я удалю тестовый контроллер из задания 13 (MInio)?

Да

2024-12-12 08:22 UTC, KirillSachkov requested changes

2024-12-12 08:22 UTC, KirillSachkov commented on backend/src/PetFamily.API/Controllers/Volunteers/Request/MovePositionPetRequest.cs
> +
лишние отступы, почаще используй crtl + k + d, чтобы ide исправляло форматирование

2024-12-12 08:22 UTC, KirillSachkov commented on backend/src/PetFamily.API/Controllers/Volunteers/VolunteersController.cs
> +    public async Task<ActionResult> MovePositionToPet(
Название метода не очень понятное, лучше MovePetPosition

2024-12-12 15:05 UTC, KirillSachkov approved these changes

2024-12-12 16:19 UTC, merged